# Site settings
title: Yathartha Joshi
name: Yathartha Joshi
subtitle: Learnings, Ramblings and Rants. In that order.
email: yathartha32@gmail.com
description: >
  A personal website about technical things I find useful. Also, random ramblings and rants.
baseurl: ""
url: "https://Yathartha22.github.io/"
github_username:  Yathartha22
disqus_baseurl: "https://Yathartha22.github.io/"
permalink: :title
cover: "/assets/header_image.jpg"
logo: "/assets/nr-logo.jpg"
ga_tracking_id: "UA-82647777-1"


# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
version: 1.0.1

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yathartha Joshi"


# About/contact
author:
  name:             Yathartha Joshi
  github:           Yathartha22
  email:            yathartha32@gmail.com
  linkedin:         Yathartha Joshi
  gravatar_md5:     dcef76307de7fa9058c7f9d33a8277aa

# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks